force-app/main/default/objects/Category_Template__c/Category_Template__c.object-meta.xml
<CustomObject>
    <label>Category Template</label>
    <nameField>
        <label>Category Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category_Template__c/fields/Document_Category__c.field-meta.xml
<CustomField>
    <fullName>Document_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Category</label>
    <referenceTo>Document_Category__c</referenceTo>
    <relationshipLabel>Category Templates</relationshipLabel>
    <relationshipName>Category_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Category_Template__c.field-meta.xml
<CustomField>
    <fullName>Category_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category Template</label>
    <referenceTo>Category_Template__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Category__c/Document_Category__c.object-meta.xml
<CustomObject>
    <label>Document Category</label>
    <nameField>
        <label>Document Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Account_Trigger_Helper.cls
public without sharing class Account_Trigger_Helper{
    public Static boolean runTrigger = true;
    public static void CreateDocumentCategories(List<Account> accList){
        try{
            List<Document_Category__c> docCategory = new List<Document_Category__c>();
            List<Category_Template__c> document_cat_list = new List<Category_Template__c>();
            List<Document__c> DocCatListToBeInserted = new List<Document__c>();
            
            docCategory = [Select Id From Document_Category__c Where Name = 'Basic Doc Category'];
            if(!docCategory.isEmpty()){
                document_cat_list = [Select Id, Name From Category_Template__c Where Document_Category__c = :docCategory[0].Id];
            }

            for (Account acc : accList){
                if(!document_cat_list.isEmpty()){
                    for (Category_Template__c catTemplate : document_cat_list){
                        Document__c doc = new Document__c();
                        doc.Name = catTemplate.Name;
                        doc.Account__c = acc.Id;
                        doc.Category_Template__c = catTemplate.Id;
                        DocCatListToBeInserted.add(doc);
                    }
                }
            }
            if(!DocCatListToBeInserted.isEmpty())
                insert DocCatListToBeInserted;
            
        }catch(exception ex){
            system.debug('Errror-->'+ex.getMessage());
            system.debug('Errror-->'+ex.getCause());
            system.debug('Errror-->'+ex.getLineNumber());
        }
    }
}