force-app/main/default/objects/Company_Specifications__c/fields/CIN__c.field-meta.xml
<CustomField>
    <fullName>CIN__c</fullName>
    <label>CIN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <label>GSTIN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Specifications__c/fields/SAC__c.field-meta.xml
<CustomField>
    <fullName>SAC__c</fullName>
    <label>SAC</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <displayFormat>IN-{0000}</displayFormat>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PRODUCT_CODE__c.field-meta.xml
<CustomField>
    <fullName>PRODUCT_CODE__c</fullName>
    <label>PRODUCT CODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TaxInvoiceHelper.cls
global without sharing class TaxInvoiceHelper {
    
    public  String InvoiceId {get; set;}
    public  Opportunity oppDetails {get; set;} 
    public  Invoice__c invoiceRecord {get; set;} 
    public  Company_Specifications__c companyDetails {get; set;} 
    public  Lead leadDetails {get; set;} 

    global TaxInvoiceHelper(){
        InvoiceId =  ApexPages.CurrentPage().getparameters().get('id');
        system.debug('InvoiceId-->'+InvoiceId);
        
        
        companyDetails = [Select Name__c,Address__c,SAC__c,CIN__c,Email__c,GSTIN__c,PAN__c,Phone__c From Company_Specifications__c ];
        system.debug('companyDetails-->'+companyDetails);
        invoiceRecord = [Select Opportunity__c,Invoice_Number__c,Initiated_Date__c,Invoice_Due_Date__c,PRODUCT_CODE__c,Amount__c,Opportunity__r.Description,Opportunity__r.Amount,Lead__c,Lead__r.Amount__c,Lead__r.Product__r.ProductCode From Invoice__c where Id =: InvoiceId ];
        system.debug('invoiceRecord-->'+invoiceRecord);
        
        if(invoiceRecord.Opportunity__c != null){
            oppDetails = [Select Id,Name,Account.Name, Account.GST_number__c, Account.PAN__c, Account.CIN__c,Account.Phone,Account.Email__c,Account.BillingStreet,Description,Amount, 
            Account.BillingCity, Account.BillingState,Account.ShippingStreet,Account.ShippingCity, Account.ShippingState,Account.ShippingPostalCode,Account.BillingPostalCode
            ,Account.BillingCountry,(Select Name,TotalPrice From OpportunityLineItems limit 1) From Opportunity where id =: invoiceRecord.Opportunity__c];
        }else{
            
        }
       system.debug('oppDetails-->'+oppDetails);
    }
    @future(callout=true)
    global static void attachPdf(string recordId){
        
        try{
            String reciepientEmail;
            PageReference pdfPage;
            if([Select id,Profile.UserLicense.Name from User where Id=: UserInfo.getUserId()].Profile.UserLicense.Name == 'Guest User License'){
                //site 
                pdfPage  = new PageReference(Label.Site_URL);
            }else{
                //internal user
                pdfPage = Page.TaxInvoice;
            }            
            
            pdfPage.getParameters().put('id',recordId);
            system.debug('recordId-->'+recordId);
            Blob pdfBlob; 
            pdfBlob = pdfPage.getContent(); 
           
            Attachment attach = new Attachment(parentId = recordId, Name = 'TaxInvoice.pdf', body = pdfBlob); 
            insert attach;
            reciepientEmail = [Select Opportunity__r.Account.Email__c From Invoice__c where Id =: recordId].Opportunity__r.Account.Email__c;
            system.debug('reciepientEmail :: '+ reciepientEmail);
            if(!string.isBlank(reciepientEmail)){
                EmailIUtility.sendEmailForPaymentSuccess(reciepientEmail, Constants.RAZOR_PAY_SUCCESS_EMAIL_OPPORTUNITY, Constants.OPPORTUNITY, recordId);
            }
            
        }
        catch(exception ex){
            system.debug('Error-->'+ex.getLineNumber());
            system.debug('Error-->>'+ex.getMessage());
        }
        
    }    
}