force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/CGST__c.field-meta.xml
<CustomField>
    <fullName>CGST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CGST</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IGST__c.field-meta.xml
<CustomField>
    <fullName>IGST__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IGST</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Tracking__c/User_Tracking__c.object-meta.xml
<CustomObject>
    <label>User Tracking</label>
    <nameField>
        <displayFormat>UT-{0000000}</displayFormat>
        <label>User Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Tracking__c/fields/Checkin_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Checkin_Datetime__c</fullName>
    <label>Checkin Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerTestClass.cls
@isTest
public class InvoiceTriggerTestClass {
    
    @isTest(SeeAllData=true)
    public static void testInvoice(){
        Invoice__c inv = new Invoice__c();
        inv.CGST__c = true;
        insert inv;
        inv.IGST__c = true;
        update inv;
    }
    
    @isTest
    public static void insertUserTrackingRec(){
        User_Tracking__c userTrackRec = new User_Tracking__c();
        userTrackRec.Checkin_Datetime__c = system.now();
        insert userTrackRec;
    }
    //Lead
    @isTest
    public static void insertLeadRec(){
        Lead leadRec = new Lead();
        leadRec.LAstName = 'Abc';
        leadRec.Company = 'Abc';
        insert leadRec;
        Attachment attachmentRec = new Attachment();
        attachmentRec.Name = 'Abc';
        attachmentRec.Body = blob.valueOf('asdsffsf');
        attachmentRec.ParentId = leadRec.Id;
        insert attachmentRec;
    }
    
    //Account
    @isTest
    public static void insertAccountRec(){
        Account accountRec = new Account();
        accountRec.Name = 'Abc';
        insert accountRec;
    }
    //TaskTrigger
    @isTest
    public static void insertTaskRec(){
        Task taskRec = new Task();
        taskRec.Subject = 'Abc';
        insert taskRec;
    }
    //OpportunityTrigger
    @isTest(SeeAllData=true)
    public static void insertOpportunityRec(){
        Opportunity OpportunityRec = new Opportunity();
        OpportunityRec.Description = 'Abc';
        OpportunityRec.Name = 'sdfghjk';
        OpportunityRec.CloseDate = system.today();
        OpportunityRec.StageName = 'Qualification';
        insert OpportunityRec;
        OpportunityLineItem OpportutnityLineItemRec = new OpportunityLineItem();
        OpportutnityLineItemRec.Description = 'Abc';
        OpportutnityLineItemRec.OpportunityId = OpportunityRec.Id;
        OpportutnityLineItemRec.Quantity = 2;
        OpportutnityLineItemRec.TotalPrice = 100;
        OpportutnityLineItemRec.PricebookEntryId = [Select Id from PricebookEntry where isActive = true limit 1].ID;
        insert OpportutnityLineItemRec;
    }
}