force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intiated</fullName>
            </value>
            <value>
                <fullName>Realized</fullName>
            </value>
            <value>
                <fullName>Not realized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHelper.cls
public without sharing class InvoiceTriggerHelper {
    static InvoiceTriggerHelper handlerInstance;
    public static InvoiceTriggerHelper getInstance() {
        if(handlerInstance == null) 
            handlerInstance = new InvoiceTriggerHelper();
        return handlerInstance;
    }
    public void paymentStatusUpdated(Map<Id, Invoice__c> oldMap, Map<Id, Invoice__c> newMap){
        try{
            set<Id> invoiceIds = new Set<Id>();
            
            for(Invoice__c invoiceRec : newMap.values()){
                if(invoiceRec.Status__c != oldMap.get(invoiceRec.Id).Status__c && invoiceRec.Status__c == Constants.INVOICE_STATUS_REALIZED){
                    invoiceIds.add(invoiceRec.Id);
                }
            }
            if(!invoiceIds.isEmpty()){
                for(Id invoiceRecId : invoiceIds){
                    TaxInvoiceHelper.attachPdf(invoiceRecId);
                }
            }
        }catch(exception ex){
            system.debug('Errror-->'+ex.getMessage());
            system.debug('Errror-->'+ex.getCause());
            system.debug('Errror-->'+ex.getLineNumber());
        }
    }
}